name: "Project setup"
description: "This action checks out the commit, sets up Node and pnpm, then installs the project"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      id: setup-pnpm
      uses: pnpm/action-setup@v4 # reads version from packageManager field in package.json

    - name: Setup node
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: Install dependencies
      id: install-dependencies
      run: pnpm install
