name: "Project setup"
description: "This action checks out the commit, sets up Node and pnpm, then installs the project"
inputs:
  pre-install-script: # id of input
    description: "File path from root of project to a (JavaScript) pre-install script to run prior to installing dependencies"
    required: false
    default: ""
  pre-install-context:
    description: "JSON string of an object, will be provided to environment of pre-install script"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      id: setup-pnpm
      uses: pnpm/action-setup@v4 # reads version from packageManager field in package.json

    - name: Setup node
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: pnpm

    - name: Run pre-install script
      if: ${{ inputs.pre-install-script != '' }}
      id: preinstall-script
      shell: bash
      run: node ${{ inputs.pre-install-script }}
      env: ${{ fromJSON(inputs.pre-install-context) }}

    # - name: Install dependencies
    #   id: install-dependencies
    #   shell: bash
    #   run: pnpm install
