name: Publish Snapshot

on:
  workflow_call:

jobs:
  publish-snapshot:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # If on the changesets PR branch, there are no changeset files, need to grab those from master
      - name: Grab master branch changesets
        if: github.ref_name == 'changeset-release/master'
        uses: actions/checkout@v4
        with:
          ref: master
          sparse-checkout: .changeset

      - name: Setup project
        uses: ./.github/actions/setup-action

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: built-package
          path: build

      - name: Release snapshot
        uses: jvilders/changesets-snapshot-action
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
