name: Pull request workflow
on:
  pull_request:
    branches: master

jobs:
  cache-dependencies:
    uses: ./.github/workflows/cache-dependencies.yml

  code-checks:
    uses: ./.github/workflows/code-checks.yml
    needs: cache-dependencies

  build:
    uses: ./.github/workflows/build.yml
    needs: code-checks

  publish-snapshot:
    uses: ./.github/workflows/publish-snapshot.yml
    needs: build
    secrets: inherit
