name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  cache-dependencies:
    uses: ./.github/workflows/cache-dependencies.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: cache-dependencies

  release:
    permissions:
      contents: write # to create release
      issues: write # to post issue comments
      pull-requests: write # to create pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-action

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: built-package
          path: build

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
